Repository Laravel-Backpack/basset, pull requests merged in 2023-08, with the labels that each got.

#72 Basset check command
  .github/workflows/ci.yml
  composer.json
  readme.md
  src/BassetManager.php
  src/BassetServiceProvider.php
  src/Console/Commands/BassetCheck.php
  src/Console/Commands/BassetInstall.php
  tests/Helpers/basset-test.js
Labels: Priority: MUST, bug

#85 Feat: Add basset() helper function
  composer.json
  readme.md
  src/Helpers/functions.php
  tests/Feature/BassetBlockTest.php
  tests/Feature/BassetTest.php
  tests/Feature/DevModeTest.php
  tests/Feature/LoadOnceTest.php
  tests/Feature/OutputTest.php
  tests/Pest.php
Labels: Priority: MUST, Priority: SHOULD, Size: M

#90 Support for basset helper function on basset:cache command
  src/Console/Commands/BassetCache.php
Labels: Priority: SHOULD
