Repository Laravel-Backpack/basset, pull requests merged in 2023-07, with the labels that each got.

#60 Add PHP zip extension notes
  composer.json
  readme.md
Labels: Priority: MUST, Priority: SHOULD

#66 Fix issue with reading .tar.gz archives
  src/Helpers/Unarchiver.php
Labels: Priority: MUST, bug

#68 Changed to relative paths to avoid errors with the APP_URL
  src/BassetManager.php
  src/Helpers/CacheMap.php
  src/config/backpack/basset.php
Labels: Priority: MUST, Priority: SHOULD

#73 Fix basset fresh concurrent calls — Drop L9 support
  .github/workflows/ci.yml
  composer.json
  src/Console/Commands/BassetFresh.php
Labels: Priority: MUST, Size: S

#74 Added "basset" disk
  src/BassetServiceProvider.php
  src/Console/Commands/BassetCheck.php
Labels: Priority: MUST
