Repository Laravel-Backpack/basset, pull requests merged in 2024-04, with the labels that each got.

#92 [FEATURE] Added BassetCachedEvent
  readme.md
  src/BassetManager.php
  src/Events/BassetCachedEvent.php
Labels: Feature

#91 [Feature] Support for SVGs, images and more
  readme.md
  src/BassetManager.php
  src/Helpers/FileOutput.php
  src/resources/views/css.blade.php
  src/resources/views/ico.blade.php
  src/resources/views/img.blade.php
  src/resources/views/js.blade.php
  src/resources/views/object.blade.php
  src/resources/views/source.blade.php
  src/resources/views/track.blade.php
Labels: Priority: SHOULD

#118 store the file with the provided extension
  src/BassetManager.php
  src/Helpers/CacheMap.php
  src/Helpers/FileOutput.php
Labels: Priority: MUST
